In [1]:
import numpy as np
u_a = [100,200,50,400]
u_b = [50,0,0,100]
u_c = [350, 100,50,200]
exams = [u_a,u_b,u_c]
exams

[[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]

In [2]:
my_list = [i for i in range(1000000)]
my_array = np.arange(100000)

In [3]:
%time for _ in range(10): my_list2 = [x**2 for x in my_list] 

Wall time: 2.25 s


In [4]:
%time for _ in range(10): my_array2 = my_array**2

Wall time: 960 µs


In [5]:
one_dim = np.array([1,2,3,4])
print(type(one_dim))
print(one_dim.shape)
print(one_dim.ndim)

<class 'numpy.ndarray'>
(4,)
1


In [21]:
two_dim = np.array([[100,200,50,400],[50,0,0,100],[350,100,50,200]])
print("len: ", len(two_dim))
print("shape:", two_dim.shape)
print("dim:", two_dim.ndim)
print(one_dim.reshape(2,2))
print(two_dim.reshape(4,3))
print(two_dim.reshape(6,2))
print(two_dim.transpose())

len:  3
shape: (3, 4)
dim: 2
[[1 2]
 [3 4]]
[[100 200  50]
 [400  50   0]
 [  0 100 350]
 [100  50 200]]
[[100 200]
 [ 50 400]
 [ 50   0]
 [  0 100]
 [350 100]
 [ 50 200]]
[[100  50 350]
 [200   0 100]
 [ 50   0  50]
 [400 100 200]]


In [22]:
np.array(my_list)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [24]:
my_nested_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.ones((2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [35]:
np.linspace(0,5,12)

array([0.        , 0.45454545, 0.90909091, 1.36363636, 1.81818182,
       2.27272727, 2.72727273, 3.18181818, 3.63636364, 4.09090909,
       4.54545455, 5.        ])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(5)

array([0.64212417, 0.08024278, 0.61074987, 0.04680144, 0.06448497])

In [39]:
np.random.rand(5,5)

array([[0.27833244, 0.05749547, 0.27848527, 0.5784245 , 0.85703468],
       [0.48652475, 0.19793214, 0.66208682, 0.27334221, 0.3961734 ],
       [0.53634983, 0.47191928, 0.62415447, 0.11452222, 0.51907642],
       [0.62275299, 0.71287746, 0.90688047, 0.25745645, 0.49163594],
       [0.94260387, 0.81039538, 0.42503908, 0.56484229, 0.99785364]])

In [46]:
np.random.randint(1,50,10)

array([ 4, 15, 31, 10, 27, 43, 20, 29, 29, 16])

### Ćwiczenie

In [48]:
np.random.rand(10)

array([0.01698167, 0.22516664, 0.05367912, 0.74215463, 0.63398882,
       0.75861057, 0.33255276, 0.2611    , 0.77577296, 0.47792272])

In [76]:
my_lst = range(0,5)
np.array([my_lst,my_lst,my_lst,my_lst,my_lst]).transpose()

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])